### ISSUE TITLE
Adjust overall component style to design

### ISSUE THREAD

**Issue by ylembachar** [shutter-network/shutter-explorer#20]
This is to adjust the overall component style to the design provided by the design team:
- [x] [Adjust transaction detail page style](https://github.com/shutter-network/shutter-explorer/issues/29)
- [x] [Adjust system overview page style](https://github.com/shutter-network/shutter-explorer/issues/30)
- [x] [Adjust slot overview page style](https://github.com/shutter-network/shutter-explorer/issues/31)
- [x] Finalize any last styling tasks

**Comment by ylembachar** [comment]
@faheelsattar @blockchainluffy cc @fredo:
I've added here a list of remaining tasks to do on the front end styling side ordered by priority - there are probably other things I haven't listed but you can always refer to the Figma file for reference.

System Overview Page
- [ ] 1) Merge this PR: [PR](https://github.com/shutter-network/shutter-explorer/pull/40)
- [ ] 2) Chart needs to cover the full-width of the screen and need to be styled following the theme colors
- [ ] 3) Keep only the second gauge and style it with the theme colors
- [ ] 4) Keep the estimated inclusion time in the first line (not present in the Figma file), and the chart and gauge in the second line following the design in the Figma file
- [ ] 5) Align the errors to the left (you can add an error style for all errors)
- [ ] 6) Add the Keyper text in the Keyper overview card (see in the Figma file)

Slot Overview Page
- [ ] 7) Add design for tables

Transaction detail page
- [ ] 8) Add different styles for statuses
- [ ] 9) Estimated inclusion time and effective inclusion time should be converted from Unix timestamp to the user's timezone. This is not styling related but should be fixed. 

All pages:
- [ ] 10) Remove websocket errors from display
- [ ] 11) Add info icon to the tooltip. Right now, you hover and you can see the tooltip.

Header:
- [ ] 12) Add links and sub-categories to header (See website for example)

General: 
- [ ] 13) After integration work is done, make sure the data is correctly displayed on the frontend on all elements, that different error messages are properly displayed, that the data precision for the charts is correct. 
- [ ] 14) Double check any major differences between the provided design and the final result and correct them
- [ ] 15) Double check any minor differences between the provided design and the final result and correct them
- [ ] 16) The Gnosis Chain dropdown list only contains one chain. I would remove it for now.

**Important implementation notes** 
1) The unit tests are in cypress and they need to be run manually. While this is not ideal, please make sure that the tests are successful before merging a PR. 

2) You can use the Figma Dev Tools to inspect the exact styles, and Builder.io to have some help generating the code. (They have a free 30 day trial version.) However, please make sure that the code added still follows the same code structure: 
    - All components should go under the components folder, pages modules under modules, and so on
    - Use styled components and add them under the respective style file
    - Icons are in SVG format and added under the icons folder
    - Use MUI components and properties when available

3) The theme has definitions for colors and headings, please use those instead of hardcoding the colors and styles. Use the theme for any system-wide styles. This is also a WIP in the current code, feel free to correct that when you see it :-)

**Comment by ylembachar** [comment]
@faheelsattar @blockchainluffy cc @fredo summarizing here what we discussed during the meeting although some tasks are not front-end related but you can create their corresponding issues):

Faheel:
- [ ] Fixing the bug when no transaction is found after the tx is submitted
- [ ] Fix the percentage issue
- [ ] Fixing the bug with copying the transaction hash
- [ ] Work on the slot overview page

Punit:
- [ ] DB migration (you can do some testing here based on the newly generated data)
- [ ] Fixing the inclusion chart
- [ ] Fixing the cypress tests

Yousra:
I will continue working on the system overview and take on the next remaining styling tasks.

When you guys are done, feel free to pick up the next task on the list.

**Comment by ylembachar** [comment]
@faheelsattar @punit @fredo I've gathered below the last todos regarding the front-end styling:

- [ ] Test different values, make sure the data is correctly displayed on the frontend on all elements, that different error messages are properly displayed, that the data precision for the charts is correct. (punit is working on this)

Finalize sidebar styling
- [ ] the colors and spacing need to be adjusted here
- [ ] when not active, the icon should be greyed

Make header identical to the website header 
- [ ] the spacing needs to be adjusted
- [ ] the Join Movement link to be added
why did we remove the About section?

Correct other design differences
- [ ] Transaction Overview Icon should be in normal weight (now in bold)
- [ ] Fix tooltip for inclusion chart (says in seconds -> Estimated time for a transaction to be included)
- [ ] Change "Executed Transactions" to "Included Transactions" in the gauge and center it

Slot overview page: Transaction table design is a bit different than Figma file:
- [ ] card needs a line on top
- [ ] there should be no line below the field names
- [ ] the field names should be in grey

**Comment by ylembachar** [comment]
I also added some post-MVP issues:
https://github.com/shutter-network/shutter-explorer/issues/85
https://github.com/shutter-network/shutter-explorer/issues/86
https://github.com/shutter-network/shutter-explorer/issues/87
